-- auth_schema.sql
-- Tabellen für das auth-Schema

-- ============================================================================
-- BENUTZER, GRUPPEN, MANDANTEN (kivitendo-kompatibel)
-- ============================================================================
-- Spalten, Typen und Constraints entsprechen exakt dem Stand von kivitendo 4.0
-- (sql/auth_db.sql + Pg-upgrade2-auth). Eine von OSERP angelegte Auth-Datenbank
-- kann dadurch unverändert von kivitendo mitbenutzt werden — und umgekehrt.
--
-- IDs sind "GENERATED BY DEFAULT AS IDENTITY": PostgreSQL legt dazu die Sequenzen
-- auth.user_id_seq, auth.group_id_seq, auth.clients_id_seq und
-- auth.master_rights_id_seq an, die kivitendo selbst per nextval() anspricht.
-- "BY DEFAULT" (nicht ALWAYS), weil kivitendo IDs teils explizit einfügt.
--
-- Reihenfolge beachten: referenzierte Tabellen zuerst (der Update-Mechanismus
-- legt fehlende Tabellen in Dateireihenfolge an).

CREATE TABLE auth."user" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text NOT NULL UNIQUE,
    password text
);

COMMENT ON TABLE auth."user" IS 'Benutzerkonten (Login + Passwort-Hash); Stammdaten liegen in auth.user_config';
COMMENT ON COLUMN auth."user".login IS 'Anmeldename (eindeutig)';
COMMENT ON COLUMN auth."user".password IS 'Passwort-Hash im kivitendo-Format {PBKDF2}salt:hash';

CREATE TABLE auth."group" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text
);

COMMENT ON TABLE auth."group" IS 'Berechtigungsgruppen';

CREATE TABLE auth.clients (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    dbhost text NOT NULL,
    dbport integer NOT NULL DEFAULT 5432,
    dbname text NOT NULL,
    dbuser text NOT NULL,
    dbpasswd text NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    task_server_user_id integer REFERENCES auth."user" (id),
    UNIQUE (dbhost, dbport, dbname)
);

COMMENT ON TABLE auth.clients IS 'Mandanten (Firmen) mit den Zugangsdaten ihrer Firmen-Datenbank';
COMMENT ON COLUMN auth.clients.is_default IS 'Vorausgewählter Mandant in der Anmeldemaske (nur einer)';
COMMENT ON COLUMN auth.clients.task_server_user_id IS 'Benutzer, unter dem der kivitendo-Task-Server läuft (nur kivitendo)';

CREATE TABLE auth.user_group (
    user_id integer NOT NULL REFERENCES auth."user" (id) ON DELETE CASCADE,
    group_id integer NOT NULL REFERENCES auth."group" (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, group_id)
);

COMMENT ON TABLE auth.user_group IS 'Gruppenmitgliedschaften der Benutzer';

CREATE TABLE auth.group_rights (
    group_id integer NOT NULL REFERENCES auth."group" (id) ON DELETE CASCADE,
    "right" text NOT NULL,
    granted boolean NOT NULL,
    PRIMARY KEY (group_id, "right")
);

COMMENT ON TABLE auth.group_rights IS 'Rechte je Gruppe (granted = erteilt)';

CREATE TABLE auth.user_config (
    user_id integer NOT NULL REFERENCES auth."user" (id) ON DELETE CASCADE,
    cfg_key text NOT NULL,
    cfg_value text,
    PRIMARY KEY (user_id, cfg_key)
);

COMMENT ON TABLE auth.user_config IS 'Benutzerstammdaten und -einstellungen als Schlüssel/Wert (name, email, dateformat, ...)';

CREATE TABLE auth.clients_users (
    client_id integer NOT NULL REFERENCES auth.clients (id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES auth."user" (id) ON DELETE CASCADE,
    PRIMARY KEY (client_id, user_id)
);

COMMENT ON TABLE auth.clients_users IS 'Welche Benutzer sich an welchem Mandanten anmelden dürfen';

CREATE TABLE auth.clients_groups (
    client_id integer NOT NULL REFERENCES auth.clients (id) ON DELETE CASCADE,
    group_id integer NOT NULL REFERENCES auth."group" (id) ON DELETE CASCADE,
    PRIMARY KEY (client_id, group_id)
);

COMMENT ON TABLE auth.clients_groups IS 'Welche Gruppen (und damit Rechte) in welchem Mandanten gelten';

CREATE TABLE auth.master_rights (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position integer NOT NULL,
    name text NOT NULL UNIQUE,
    description text NOT NULL,
    category boolean NOT NULL DEFAULT false
);

COMMENT ON TABLE auth.master_rights IS 'Katalog aller vergebbaren Rechte; category = Überschrift (kein Recht). Seed: auth_data/master_rights.csv';

CREATE TABLE auth.schema_info (
    tag text NOT NULL PRIMARY KEY,
    login text,
    itime timestamp without time zone DEFAULT now()
);

COMMENT ON TABLE auth.schema_info IS 'Angewendete kivitendo-Upgradeskripte der Auth-DB. Seed: auth_data/schema_info.csv (Stand kivitendo 4.0)';

CREATE TABLE auth.session (
    id text NOT NULL PRIMARY KEY,
    ip_address inet,
    mtime timestamp without time zone,
    api_token text
);

COMMENT ON TABLE auth.session IS 'kivitendo-Sitzungen (OSERP nutzt auth.session_oserp)';

CREATE TABLE auth.session_content (
    session_id text NOT NULL REFERENCES auth.session (id) ON DELETE CASCADE,
    sess_key text NOT NULL,
    sess_value text,
    auto_restore boolean DEFAULT false,
    PRIMARY KEY (session_id, sess_key)
);

COMMENT ON TABLE auth.session_content IS 'kivitendo-Sitzungsinhalte';

-- ============================================================================
-- SESSION MANAGEMENT
-- ============================================================================

CREATE TABLE auth.session_oserp (
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    session_id text PRIMARY KEY,
    user_id integer NOT NULL,
    client_id integer NOT NULL,
    active timestamp without time zone DEFAULT now(),
    remember_me boolean NOT NULL DEFAULT false
);

COMMENT ON TABLE auth.session_oserp IS 'Sitzungsverwaltung für OpensourceERP';
COMMENT ON COLUMN auth.session_oserp.id IS 'Primärschlüssel (automatisch generiert)';
COMMENT ON COLUMN auth.session_oserp.session_id IS 'Eindeutige Session-ID';
COMMENT ON COLUMN auth.session_oserp.user_id IS 'Referenz zum Benutzer';
COMMENT ON COLUMN auth.session_oserp.client_id IS 'Referenz zum Mandanten';
COMMENT ON COLUMN auth.session_oserp.active IS 'Letzter Aktivitätszeitpunkt der Session';
COMMENT ON COLUMN auth.session_oserp.remember_me IS '"Angemeldet bleiben": Cookie überlebt Browser-Close, Session lebt bis 120h Inaktivität';

-- ============================================================================
-- SESSION CLEANUP FUNCTION & TRIGGER
-- ============================================================================

CREATE OR REPLACE FUNCTION auth.cleanup_session_oserp()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM auth.session_oserp
    WHERE active < NOW() - INTERVAL '120 hours';
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION auth.cleanup_session_oserp() IS 'Löscht automatisch Sessions die länger als 120 Stunden inaktiv sind';

CREATE OR REPLACE TRIGGER trigger_cleanup_session_oserp
AFTER INSERT OR UPDATE
ON auth.session_oserp
FOR EACH STATEMENT
EXECUTE FUNCTION auth.cleanup_session_oserp();

COMMENT ON TRIGGER trigger_cleanup_session_oserp ON auth.session_oserp IS 'Trigger für automatische Session-Bereinigung';

-- ============================================================================
-- LOGIN-VERSUCHE / RATE-LIMITING
-- ============================================================================
-- Bremst Brute-Force-Anmeldungen. login() zaehlt die Fehlversuche je
-- Benutzername und je IP im 15-Minuten-Fenster und blockiert ab einer
-- Schwelle. Die Anwendung ueberspringt das Limit, solange diese Tabelle in
-- einer Mandanten-Auth-DB noch fehlt (fail open) — die uebrige Login-Haertung
-- wirkt unabhaengig davon.

CREATE TABLE auth.login_attempts (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login text,
    ip text,
    success boolean NOT NULL DEFAULT false,
    attempted_at timestamp without time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE auth.login_attempts IS 'Protokoll der Anmeldeversuche fuer das Rate-Limiting';
COMMENT ON COLUMN auth.login_attempts.login IS 'Eingegebener Benutzername (kann auch unbekannt sein)';
COMMENT ON COLUMN auth.login_attempts.ip IS 'IP-Adresse des Aufrufers';
COMMENT ON COLUMN auth.login_attempts.success IS 'Ob der Versuch erfolgreich war';
COMMENT ON COLUMN auth.login_attempts.attempted_at IS 'Zeitpunkt des Versuchs';

CREATE INDEX IF NOT EXISTS idx_login_attempts_login ON auth.login_attempts (login, attempted_at);
CREATE INDEX IF NOT EXISTS idx_login_attempts_ip    ON auth.login_attempts (ip, attempted_at);

-- Alte Zeilen automatisch entfernen (Muster wie bei session_oserp)
CREATE OR REPLACE FUNCTION auth.cleanup_login_attempts()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM auth.login_attempts
    WHERE attempted_at < NOW() - INTERVAL '24 hours';
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION auth.cleanup_login_attempts() IS 'Loescht Login-Versuche aelter als 24 Stunden';

CREATE OR REPLACE TRIGGER trigger_cleanup_login_attempts
AFTER INSERT
ON auth.login_attempts
FOR EACH STATEMENT
EXECUTE FUNCTION auth.cleanup_login_attempts();

COMMENT ON TRIGGER trigger_cleanup_login_attempts ON auth.login_attempts IS 'Trigger fuer automatische Bereinigung der Login-Versuche';
